"""initial

Revision ID: ec70e82a3516
Revises: 
Create Date: 2026-02-22 01:46:12.308877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec70e82a3516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oficios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oficio', sa.String(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('remitente', sa.String(), nullable=False),
    sa.Column('destinatario', sa.String(), nullable=False),
    sa.Column('acusado', sa.Boolean(), nullable=False),
    sa.Column('hipervinculo', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('antecedentes', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cursos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instructor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topico', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cursos_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('cursos_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('oficios')
    # ### end Alembic commands ###
